# Generated by Django 4.1.7 on 2023-06-13 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited_employees',
            name='invite_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
