# Generated by Django 4.2.2 on 2023-07-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_invited_employees_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='employees',
        ),
    ]
