# Generated by Django 4.2.2 on 2023-07-20 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_remove_business_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited_employees',
            name='primary_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'business': django.db.models.expressions.OuterRef('business')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.business_job_roles'),
        ),
        migrations.AlterField(
            model_name='invited_employees',
            name='secondary_roles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'business': django.db.models.expressions.OuterRef('business')}, related_name='secondary_roles', to='businesses.business_job_roles'),
        ),
    ]
