# Generated by Django 4.1.7 on 2023-06-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_business_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='business_invite_code',
        ),
    ]
