# Generated by Django 4.2.2 on 2023-07-19 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_invited_employees_invite_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_flag', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.invited_employees')),
            ],
        ),
    ]
