# Generated by Django 4.2.2 on 2023-07-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_alter_time_off_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_off',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Date created'),
        ),
    ]
