# Generated by Django 4.1.7 on 2023-06-13 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Skeleton_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncertain_shift_end', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business_job_roles')),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Skeleton_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('start_block', models.CharField(max_length=500)),
                ('end_block', models.CharField(max_length=500)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('shift_skeleton_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shift_skeleton_master')),
            ],
        ),
    ]
