# Generated by Django 4.2.2 on 2023-06-23 00:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Outline_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_employee_count', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('shift_slots', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, validators=[schedules.models.validate_range_and_unique])),
                ('shift_class_slots', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, validators=[schedules.models.validate_range_and_unique])),
                ('shift_id', models.CharField(blank=True, null=True)),
                ('shift_skeleton_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shift_skeleton_master')),
            ],
        ),
    ]
