# Generated by Django 4.2.2 on 2023-06-27 00:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import schedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_invited_employees_invite_code'),
        ('schedules', '0002_shift_outline_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_slots', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, validators=[schedules.models.validate_unique])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.invited_employees')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business_job_roles')),
            ],
        ),
    ]
