# Generated by Django 4.2.2 on 2023-06-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_actual_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_shifts',
            name='week_multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
