# Generated by Django 4.2.4 on 2023-08-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_invited_employees_primary_role_and_more'),
        ('schedules', '0005_actual_shifts_related_shift_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Single_Templated_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.IntegerField()),
                ('start_slot', models.IntegerField()),
                ('end_slot', models.IntegerField()),
                ('day_of_week', models.CharField()),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shift_template')),
            ],
        ),
    ]
