# Generated by Django 4.2.4 on 2023-08-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_invited_employees_primary_role_and_more'),
        ('schedules', '0006_shift_template_single_templated_shift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift_Template',
            new_name='Schedule_Template',
        ),
    ]
